project:
  type: website
  output-dir: docs
  preview:
    port: 7771
    browser: false  
  resources:
    - "data/*.mp3"
    - "data/*.wav"
    - "data/LibriSpeech/*.mp3"

  render:
    - "*.qmd"
    - "!*.Rmd"
    - "!data/old/*.qmd"

lang: ko
date-format: "YYYY년 MM월 DD일"


website:
  title: "챗GPT AI"
  favicon: "assets/android-chrome-192x192.png"
  google-analytics: "UA-229551680-1"
  search:
    location: navbar
    type: overlay
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "기본기"
        contents:
          - index.qmd
          - positron.qmd
          - API.qmd
          - rstats.qmd
      - section: "AI 코딩"
        contents:
          - langchain.qmd
          - API_openai.qmd
          - code_interpreter.qmd
      - section: "LLM"
        contents:
          - ollama.qmd
          - hf.qmd
      - section: "데이터베이스"
        contents:
          - database.qmd
      - section: "자동화"
        contents:
          - llm_ops.qmd
          - gh_action.qmd
          - target.qmd
          - gcs.qmd
      - section: "사례"
        contents:
          - chat.qmd
          - openai_apps.qmd
          - yt_openai.qmd
      - section: "참고문헌"
        contents:
          - references.qmd

    right:
      - icon: github
        href: https://github.com/bit2r/gpt-ai
      - href: https://r2bit.com
        text: "R사용자회"
      - icon: github
        text: "Open Assistant"
        href: https://github.com/LAION-AI/Open-Assistant
      - text: "RTutor"
        href: https://rtutor.ai/
  page-footer:
    center: |
      [한국 R 사용자회](mailto:admin@r2bit.com)
    left: |
      [Quarto](https://quarto.org/) 개발
    right: |
      [Github 코드 저장소](https://github.com/bit2r/gpt-ai)
    background: "#2780e3"

# ---------------------------------- #
lightbox: true

# ---------------------------------- #
filters:
  - shinylive
  - webr
  - pyodide  

format:
  html:
    resources:
      - shinylive-sw.js
    theme:
      light: flatly
      dark: darkly
    css: assets/quarto.css
    code-link: true
    code-fold: show
    code-tools: true
    code-block-bg: "white"
    code-block-border-left: "#31BAE9"
    highlight-style: github
    toc: true
    mermaid-format: png
    # fig-width: 8 #https://quarto.org/docs/computations/execution-options.html#figure-options
    # fig-height: 6
    mermaid:
      theme: neutral # https://quarto.org/docs/authoring/diagrams.html#mermaid-theming
    


bibliography: assets/references.bib
csl: assets/apa-single-spaced.csl
link-citations: true

execute:
  freeze: auto

editor_options: 
  chunk_output_type: console  
          